name: Run Attack Script

on: [push]

jobs:
  attack:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install PHP
        uses:shivammathur/setup-php@v2
        with:
          php-versions: '8.1'

      - name: Run Attack Script
        run: php auto-attack.php
