name: Run Attack Script

on:
  workflow_dispatch: # Pour tester manuellement
  push:
    branches:
      - main # Exécution automatique à chaque push sur la branche main
  pull_request:
    branches:
      - main

jobs:
  attack:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up PHP
        uses:shivammathur/setup-php@v2
        with:
          php-version: '8.1'

      - name: Run Attack Script
        run: |
          php auto-attack.php
